### ISSUE TITLE
Can't sync xerolinux repository

### ISSUE THREAD

**Issue by latinblood4109** [xerolinux/xerolinux_repo#1]
When I issue the command "sudo pacman -Suy",  this is the error that appears:

       error: failed retrieving file 'xerolinux_repo.db' from repos.xerolinux.xyz : The requested URL returned error: 404
       error: failed to synchronize all databases (unexpected error)

This start this morning, because of that, I can't install certain apps

**Comment by TechXero** [comment]
@latinblood4109 Read pinned messages
